from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
	url(r'^$','admin.views.index', name='index'),
	url(r'^login$', 'admin.views.admin_login', name='login'),
	url(r'^logout$', 'admin.views.admin_logout', name='logout'),
	url(r'^registro', include('register.urls')),
	url(r'^matriculas', include('enrollment.urls')),
	url(r'^recursos',include('custom.urls')),
	url(r'^pensum',include('pensum.urls')),
	url(r'^control',include('control.urls')),
	url(r'^configuracion$','admin.views.configuracion', name='configuracion'),
	url(r'^reportes',include('report.urls')),
	url(r'^boletin$','admin.views.boletin', name='boletin'),
	url(r'^buscarBoletin$','admin.views.buscarBoletin', name='buscarBoletin'),
	url(r'^crearBoletin$','admin.views.crearBoletin', name='crearBoletin'),
	url(r'^usoPlataforma$','admin.views.usoPlataforma', name='usoPlataforma'),
	url(r'^buscarEstadistica$','admin.views.buscarEstadistica', name='buscarEstadistica'),
	url(r'^/logros$','admin.views.logros', name='logros'),
	url(r'^/actividades$','admin.views.actividades', name='actividades'),
	url(r'^/indicadores$','admin.views.indicadores', name='indicadores'),
	url(r'^/asistencia$','admin.views.asistencia', name='asistencia'),
	url(r'^/observador$','admin.views.observador', name='observador'),
	url(r'^/herramienta$','admin.views.herramienta', name='herramienta'),
	url(r'^/api$','admin.views.api', name='api'),

)